login page added
king-11/P2P pull request #9
Opened 2020-09-06 12:48 UTC by Ojusbhutani

2020-09-06 17:53 UTC, m-e-l-u-h-a-n commented
@Ojusbhutani 
I can't see any changes in the file.

2020-09-07 02:26 UTC, m-e-l-u-h-a-n commented on pages/login.vue
> +        <v-col cols="12" sm="8" md="8">
only `sm="8"` would have done what you needed

2020-09-07 03:58 UTC, m-e-l-u-h-a-n commented on pages/login.vue
> +                          v-model="Email"
#### About all the textfields:
- Add minimum length rules to simple text fields like firstname
- Add a regex validation rule for email
- for password field provide an option to show the password upon user's request.
    - append an icon for toggling display of password.

2020-09-07 04:00 UTC, m-e-l-u-h-a-n commented on pages/login.vue
> +                          <h4 class="text-center mt-3">Forgot your password</h4>
No need to add margin to button text, centered text look good.
Add primary color to the button.

2020-09-07 04:07 UTC, m-e-l-u-h-a-n commented on pages/login.vue
> +                      <v-btn rounded dark>CREATE ACCOUNT</v-btn>
**Method addition required:**
Upon clicking the sign in and create account button a method should be called which calls a method to check if all the fields are filled correctly and notify users accordingly it is the required even for most basic forms.

2020-09-07 04:18 UTC, m-e-l-u-h-a-n requested changes
Great work on the design. :partying_face: :fire: :partying_face: 
Apart from the changes i mentioned in code one more thing need to covered:
#### Current Behaviour
    - In small screen devices the images gets stacked just below the div.
#### Expected Behaviour
    - image should not be visible in small screen devices, instead you could show small text with an alternative option to login or signup with a link.

2020-09-09 20:28 UTC, m-e-l-u-h-a-n commented on pages/login.vue
> +                          :rules="[rules.minlength]"
I think password's minimum length should be 6 or 8 not zero.

2020-09-09 20:29 UTC, m-e-l-u-h-a-n commented on pages/login.vue
> +                          id="password"
We need two password fields for signup to confirm the correctness of passwords.

2020-09-09 21:14 UTC, m-e-l-u-h-a-n reviewed
@king-11 
For the latest commit following changes are suggested:
- Two password fields in signup page(currently only one).
- password min-length check should be of 6 or 8 and not zero.
So you may consider merging or... implementing these changes before merging.

2020-09-11 14:26 UTC, m-e-l-u-h-a-n approved these changes
This pr can be merged now but has extra previous commits.

2020-09-12 17:30 UTC, king-11 commented
Will need to rebase it i guess most the commit message aren't pretty clear as to that they do.

2020-09-15 16:23 UTC, m-e-l-u-h-a-n commented
@king-11 
Before the latest commit I told him to do interactive rebase but there were options for only those commits which were not pushed to remote. Probably interactive rebase can only be done for commits which have not been pushed. I think we would have to squash and merge from github itself.

2020-09-15 17:17 UTC, king-11 commented
After pushing it requires force pushing again if we interactive rebase I missed that in the dev talk because, not a good thing to do. But nevermind will do squash and merge

2020-09-15 17:17 UTC, merged